spring:
  profiles:
    active: dev
  datasource:
    #    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://43.139.148.247:3306/color_sound?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.sound-path}
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lisery.color_sound.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8080
  max-http-header-size: 8192